## Selecting the best SMLCM

I ran the models from the script 'SMLCM_functions.ipynb' using the training and testing data. 

In [1]:
import joblib
import pandas as pd
import numpy as np

### Calling functions from SMLCM_functions.ipynb

In [2]:
%run ./SMLCM_functions.ipynb

### Loading the training and testing data sets

In [6]:
# Loading data from excel sheets
training=pd.read_excel("B_OutputData/trainingTASS_data.xlsx")
testing=pd.read_excel("B_OutputData/testingTASS_data.xlsx")

# Clean the dependent variable tweet fro training and test data
training["tweet"]=training["tweet"].apply(preprocessor)
training["tweet"]=training["tweet"].apply(tildes)
##
testing["tweet"]=testing["tweet"].apply(preprocessor)
testing["tweet"]=testing["tweet"].apply(tildes)

testing["tweet"]

## Takes the data
y_train=training["sentiment"]
x_train=training["tweet"]
y_test=testing["sentiment"]
x_test=testing["tweet"]

### Runing the Classification Models 

In [9]:
estimation( x_train , y_train , x_test , y_test , "TASS" )
scores1 = scores.copy(deep=True)

Fitting 3 folds for each of 24 candidates, totalling 72 fits
[[466  63 169]
 [466  89 386]
 [275  58 306]]
Fitting 3 folds for each of 288 candidates, totalling 864 fits
[[523   7 168]
 [559   9 373]
 [304   5 330]]
Fitting 3 folds for each of 576 candidates, totalling 1728 fits
[[402   1 295]
 [402   0 539]
 [207   0 432]]
Fitting 3 folds for each of 192 candidates, totalling 576 fits
[[466  15 217]
 [485  32 424]
 [244  20 375]]
Fitting 3 folds for each of 288 candidates, totalling 864 fits
[[490  20 188]
 [502  34 405]
 [253  25 361]]


### Saving the models

In [10]:
models=[nby1,svc,rf1,KKN,Lsvc]
model_names=["NaiveBayes","SVC","RandomF","KNeigbhbor","Linear_SVC"]
for model, name in zip(models, model_names):
    joblib.dump(model, f'C_OutputModels/{name}.sav')